### ISSUE TITLE
Add cfapi checkin

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/codeforcroatia.org#14]

**Comment by schlos** [comment]
Done
http://codeforcroatia.org/checkin-open-zagreb
http://codeforcroatia.org/checkin-code-for-croatia

**Comment by schlos** [comment]
CfAPI project:
https://github.com/codeforamerica/cfapi

Info:
https://github.com/codeforamerica/brigade/issues/352

**Comment by ondrae** [comment]
Hey @schlos email me at andrewh at codeforamerica.org and I can give you access to the data you are posting.

**Comment by ondrae** [comment]
We've also added a `&question=` attribute so that you can ask different questions every week if you want  to. See https://www.codeforamerica.org/brigade/Code-for-San-Francisco/checkin/?event=Hack+Night&question=What+do+you+most+like+doing+at+Hack+Night? for an example.
