### ISSUE TITLE
Translate strings to Croatian language

### ISSUE THREAD

**Issue by LanaPdg** [codeforcroatia/codeforcroatia.org#19]
Webpage: http://codeforcroatia.org/

- [x] generate new pot file, compare with old and merge: http://emr.ge/docs/localization/pot
- [x] add translation file to Transifex
- [x] translate strings
- [x] upload new translation upstream to [laddr repo](https://github.com/codeforcroatia/laddr/)

**Comment by schlos** [comment]
codeforcroatia.org - translation laddr 2016-11-24 07:18

![unnamed](https://user-images.githubusercontent.com/1014134/61187585-81c2fc00-a673-11e9-9fe4-5ba291055c2f.png)

**Comment by schlos** [comment]
Available for translation at https://www.transifex.com/code-for-croatia/laddr/cfc-laddr-v3/

**Comment by schlos** [comment]
Done, should be reviewed on ctc-staging-v3 and fixes applied on Transifex.

New translations added via #51
