### ISSUE TITLE
Top menu reorganisation

### ISSUE THREAD

**Issue by LanaPdg** [codeforcroatia/codeforcroatia.org#20]
![izrezak](https://cloud.githubusercontent.com/assets/16172585/24830468/ee8f5bf4-1c86-11e7-9a74-f85dbd5db3bc.JPG)

Novo: 

1. About (O nama)

- About us (http://codeforcroatia.org/about-us) 
- Mission and vision (http://codeforcroatia.org/mission)
- Local groups (http://codeforcroatia.org/pages/open_zagreb)
- Code of conduct

2. Projects (Projekti)

- We have a right to know (http://codeforcroatia.org/projects/zahtjev_za_pravo_na_pristup_informacijama)
- Open Data Day (http://codeforcroatia.org/projects/codeacross-opendataday_2017)
- Other projects (http://codeforcroatia.org/projects)

3. Join us (Pridružite se)
- How to join (http://codeforcroatia.org/how-to-help)
- How to write new project (http://codeforcroatia.org/blog/kako_napisati_novi_projekt + http://codeforcroatia.org/pages/project_guidelines#hr_HR)
- How to start your local group

4. Resources

- Blog
- Useful links (http://codeforcroatia.org/resources + add: https://www.youtube.com/watch?v=H_on0kXZ07M)
- Open Data Stack Exchange

5. Contact us

- Contact us (E-mail)
- Chat (Slack)
- Forum (Discourse)
- Meetup
- Members

**Comment by schlos** [comment]
Done with: https://github.com/codeforcroatia/codeforcroatia.org/commit/c6d0499388139c860c9a375156daacce5b720851
