### ISSUE TITLE
Update Sketeton URL

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/codeforcroatia.org#38]
everywhere you have http://skeleton.sla.slatepowered.net/ needs to be whatever host you’re deploying to

https://github.com/codeforcroatia/codeforcroatia.org/blob/d88541a6055db8f69106131e51fd5d63a6e32410/.github/workflows/holo.yml#L30

https://github.com/codeforcroatia/codeforcroatia.org/blob/d88541a6055db8f69106131e51fd5d63a6e32410/.github/workflows/holo.yml#L41

https://github.com/codeforcroatia/codeforcroatia.org/blob/d88541a6055db8f69106131e51fd5d63a6e32410/.github/workflows/holo.yml#L51

------

and then everywhere there is `/sources/scienceleadership-skeleton/` needs to be `/sources/codeforcroatia/` per per https://github.com/codeforcroatia/codeforcroatia.org/blob/master/php-config/Git.config.d/codeforcroatia.php

https://github.com/codeforcroatia/codeforcroatia.org/blob/d88541a6055db8f69106131e51fd5d63a6e32410/.github/workflows/holo.yml#L41

https://github.com/codeforcroatia/codeforcroatia.org/blob/d88541a6055db8f69106131e51fd5d63a6e32410/.github/workflows/holo.yml#L51

**Comment by themightychris** [comment]
We also discussed setting up a 3-tier deployment system, using your new v3 staging site as the deploy target for the github-driven build, and then chaining your existing staging site to that and renaming it to pre-prod.

I'll need to execute this procedure on the server for you to convert the new v3 staging site to a deploy target: http://emergenceplatform.github.io/book/guides/migrate-site-to-holobranch.html
