### ISSUE TITLE
Bug on user profile

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/codeforcroatia.org#40]
https://codeforcroatia.org/people/nevionix

`Fatal error: Call to undefined method Emergence\People\User::hasMember() in /tmp/dwoo-compiled/code-for-croatia/ea1bfea6b333a2071fb6a5edf52fdc6b0d3d9bd1.d17.php on line 27`

**Comment by 0x19** [comment]
Thanks @schlos.

Additional observation: While filling out the basic profile, after save, changes are not reflected once I go again into the edit section. I do see profile picture being accepted correctly.

**Comment by schlos** [comment]
I have prioritized this to start working on this soon - as soon as cfc-staging-v3 site gets setup properly: https://github.com/codeforcroatia/codeforcroatia.org/projects/1

**Comment by schlos** [comment]
Duplicates #44, it will be resolved when site is updated to new website version (v3). I will keep it open for tracking purposes.

**Comment by schlos** [comment]
New website version is live. Issue should not happen anymore (tried with test profile, looks OK now):
https://codeforcroatia.org/profile
